services:
  docker2mqtt:
    container_name: docker2mqtt
    image: ghcr.io/boecks/docker2mqtt-amd64:latest
    environment:
      - DESTROYED_CONTAINER_TTL=86400
      - DOCKER2MQTT_HOSTNAME=my_docker_host
      - HOMEASSISTANT_PREFIX=homeassistant
      - MQTT_CLIENT_ID=docker2mqtt
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MQTT_USER=username
      - MQTT_PASSWD=password
      - MQTT_TIMEOUT=30
      - MQTT_TOPIC_PREFIX=docker
      - MQTT_QOS=1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
